# Generated by Django 5.0.3 on 2024-03-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('reception', 'reception')], default='eur', max_length=100),
        ),
    ]
