# Generated by Django 5.0.3 on 2024-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0002_alter_reservation_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
