# Generated by Django 5.0.3 on 2024-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0004_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='online_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='real_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
