# Generated by Django 5.0.3 on 2024-04-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0006_roomtypeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='roomtype/'),
        ),
    ]
