# Generated by Django 5.0.3 on 2024-05-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0007_roomtype_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='clean',
            field=models.BooleanField(default=True),
        ),
    ]
