# Generated by Django 5.0.3 on 2024-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0008_room_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='currency_type',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('lek', 'lek')], default='eur', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('reception', 'reception')], default='online', max_length=100),
        ),
    ]
