# Generated by Django 5.0.3 on 2024-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0009_reservation_currency_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
