# Generated by Django 5.0.3 on 2024-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0010_alter_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_unique_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
