# Generated by Django 5.0.3 on 2024-05-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0011_alter_room_room_unique_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('reservation', 'room')},
        ),
    ]
