# Generated by Django 5.0.3 on 2024-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/images/'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/'),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/images/'),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='guest/images/'),
        ),
        migrations.AlterField(
            model_name='hotelmanager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/images/'),
        ),
        migrations.AlterField(
            model_name='hotelmanager',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee/images/'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/'),
        ),
    ]
