# Generated by Django 5.0.3 on 2024-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
